
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

// Load .env from the project root (two levels up from services/gateway/)
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  seed: "tsx prisma/seed.ts",
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
